package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComplaintCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintCategoryAllPropertiesEquals(ComplaintCategory expected, ComplaintCategory actual) {
        assertComplaintCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertComplaintCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintCategoryAllUpdatablePropertiesEquals(ComplaintCategory expected, ComplaintCategory actual) {
        assertComplaintCategoryUpdatableFieldsEquals(expected, actual);
        assertComplaintCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintCategoryAutoGeneratedPropertiesEquals(ComplaintCategory expected, ComplaintCategory actual) {
        assertThat(actual)
            .as("Verify ComplaintCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintCategoryUpdatableFieldsEquals(ComplaintCategory expected, ComplaintCategory actual) {
        assertThat(actual)
            .as("Verify ComplaintCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintCategoryUpdatableRelationshipsEquals(ComplaintCategory expected, ComplaintCategory actual) {
        assertThat(actual)
            .as("Verify ComplaintCategory relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
