package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComplaintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintAllPropertiesEquals(Complaint expected, Complaint actual) {
        assertComplaintAutoGeneratedPropertiesEquals(expected, actual);
        assertComplaintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintAllUpdatablePropertiesEquals(Complaint expected, Complaint actual) {
        assertComplaintUpdatableFieldsEquals(expected, actual);
        assertComplaintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintAutoGeneratedPropertiesEquals(Complaint expected, Complaint actual) {
        assertThat(actual)
            .as("Verify Complaint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintUpdatableFieldsEquals(Complaint expected, Complaint actual) {
        assertThat(actual)
            .as("Verify Complaint relevant properties")
            .satisfies(a -> assertThat(a.getComplaintNumber()).as("check complaintNumber").isEqualTo(expected.getComplaintNumber()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComplaintUpdatableRelationshipsEquals(Complaint expected, Complaint actual) {
        assertThat(actual)
            .as("Verify Complaint relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getPipeline()).as("check pipeline").isEqualTo(expected.getPipeline()))
            .satisfies(a -> assertThat(a.getStage()).as("check stage").isEqualTo(expected.getStage()))
            .satisfies(a -> assertThat(a.getAssignedDepartment()).as("check assignedDepartment").isEqualTo(expected.getAssignedDepartment())
            )
            .satisfies(a -> assertThat(a.getAssignedUser()).as("check assignedUser").isEqualTo(expected.getAssignedUser()));
    }
}
