package com.mgs.domain;

import static com.mgs.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DealAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDealAllPropertiesEquals(Deal expected, Deal actual) {
        assertDealAutoGeneratedPropertiesEquals(expected, actual);
        assertDealAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDealAllUpdatablePropertiesEquals(Deal expected, Deal actual) {
        assertDealUpdatableFieldsEquals(expected, actual);
        assertDealUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDealAutoGeneratedPropertiesEquals(Deal expected, Deal actual) {
        assertThat(actual)
            .as("Verify Deal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDealUpdatableFieldsEquals(Deal expected, Deal actual) {
        assertThat(actual)
            .as("Verify Deal relevant properties")
            .satisfies(a -> assertThat(a.getDealNumber()).as("check dealNumber").isEqualTo(expected.getDealNumber()))
            .satisfies(a ->
                assertThat(a.getDealValue()).as("check dealValue").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDealValue())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getCloseDate()).as("check closeDate").isEqualTo(expected.getCloseDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDealUpdatableRelationshipsEquals(Deal expected, Deal actual) {
        assertThat(actual)
            .as("Verify Deal relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getLead()).as("check lead").isEqualTo(expected.getLead()));
    }
}
