package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventTaskAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventTaskAssignmentAllPropertiesEquals(EventTaskAssignment expected, EventTaskAssignment actual) {
        assertEventTaskAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEventTaskAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventTaskAssignmentAllUpdatablePropertiesEquals(EventTaskAssignment expected, EventTaskAssignment actual) {
        assertEventTaskAssignmentUpdatableFieldsEquals(expected, actual);
        assertEventTaskAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventTaskAssignmentAutoGeneratedPropertiesEquals(EventTaskAssignment expected, EventTaskAssignment actual) {
        assertThat(actual)
            .as("Verify EventTaskAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventTaskAssignmentUpdatableFieldsEquals(EventTaskAssignment expected, EventTaskAssignment actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventTaskAssignmentUpdatableRelationshipsEquals(EventTaskAssignment expected, EventTaskAssignment actual) {
        assertThat(actual)
            .as("Verify EventTaskAssignment relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()))
            .satisfies(a -> assertThat(a.getAssignedTo()).as("check assignedTo").isEqualTo(expected.getAssignedTo()));
    }
}
