package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAllPropertiesEquals(EventNotification expected, EventNotification actual) {
        assertEventNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertEventNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAllUpdatablePropertiesEquals(EventNotification expected, EventNotification actual) {
        assertEventNotificationUpdatableFieldsEquals(expected, actual);
        assertEventNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAutoGeneratedPropertiesEquals(EventNotification expected, EventNotification actual) {
        assertThat(actual)
            .as("Verify EventNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationUpdatableFieldsEquals(EventNotification expected, EventNotification actual) {
        assertThat(actual)
            .as("Verify EventNotification relevant properties")
            .satisfies(a -> assertThat(a.getNotificationType()).as("check notificationType").isEqualTo(expected.getNotificationType()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationUpdatableRelationshipsEquals(EventNotification expected, EventNotification actual) {
        assertThat(actual)
            .as("Verify EventNotification relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
