package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeadSourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadSourceAllPropertiesEquals(LeadSource expected, LeadSource actual) {
        assertLeadSourceAutoGeneratedPropertiesEquals(expected, actual);
        assertLeadSourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadSourceAllUpdatablePropertiesEquals(LeadSource expected, LeadSource actual) {
        assertLeadSourceUpdatableFieldsEquals(expected, actual);
        assertLeadSourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadSourceAutoGeneratedPropertiesEquals(LeadSource expected, LeadSource actual) {
        assertThat(actual)
            .as("Verify LeadSource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadSourceUpdatableFieldsEquals(LeadSource expected, LeadSource actual) {
        assertThat(actual)
            .as("Verify LeadSource relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameSearch()).as("check nameSearch").isEqualTo(expected.getNameSearch()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeadSourceUpdatableRelationshipsEquals(LeadSource expected, LeadSource actual) {
        assertThat(actual)
            .as("Verify LeadSource relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
