package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PermissionModuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionModuleAllPropertiesEquals(PermissionModule expected, PermissionModule actual) {
        assertPermissionModuleAutoGeneratedPropertiesEquals(expected, actual);
        assertPermissionModuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionModuleAllUpdatablePropertiesEquals(PermissionModule expected, PermissionModule actual) {
        assertPermissionModuleUpdatableFieldsEquals(expected, actual);
        assertPermissionModuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionModuleAutoGeneratedPropertiesEquals(PermissionModule expected, PermissionModule actual) {
        assertThat(actual)
            .as("Verify PermissionModule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionModuleUpdatableFieldsEquals(PermissionModule expected, PermissionModule actual) {
        assertThat(actual)
            .as("Verify PermissionModule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionModuleUpdatableRelationshipsEquals(PermissionModule expected, PermissionModule actual) {
        // empty method
    }
}
