package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PipelineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPipelineAllPropertiesEquals(Pipeline expected, Pipeline actual) {
        assertPipelineAutoGeneratedPropertiesEquals(expected, actual);
        assertPipelineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPipelineAllUpdatablePropertiesEquals(Pipeline expected, Pipeline actual) {
        assertPipelineUpdatableFieldsEquals(expected, actual);
        assertPipelineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPipelineAutoGeneratedPropertiesEquals(Pipeline expected, Pipeline actual) {
        assertThat(actual)
            .as("Verify Pipeline auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPipelineUpdatableFieldsEquals(Pipeline expected, Pipeline actual) {
        assertThat(actual)
            .as("Verify Pipeline relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameSearch()).as("check nameSearch").isEqualTo(expected.getNameSearch()))
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()))
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPipelineUpdatableRelationshipsEquals(Pipeline expected, Pipeline actual) {
        assertThat(actual)
            .as("Verify Pipeline relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
