package com.mgs.domain;

import static com.mgs.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAllPropertiesEquals(Plan expected, Plan actual) {
        assertPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAllUpdatablePropertiesEquals(Plan expected, Plan actual) {
        assertPlanUpdatableFieldsEquals(expected, actual);
        assertPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanAutoGeneratedPropertiesEquals(Plan expected, Plan actual) {
        assertThat(actual)
            .as("Verify Plan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanUpdatableFieldsEquals(Plan expected, Plan actual) {
        assertThat(actual)
            .as("Verify Plan relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMaxUsers()).as("check maxUsers").isEqualTo(expected.getMaxUsers()))
            .satisfies(a -> assertThat(a.getMaxStorageMb()).as("check maxStorageMb").isEqualTo(expected.getMaxStorageMb()))
            .satisfies(a -> assertThat(a.getMaxCustomers()).as("check maxCustomers").isEqualTo(expected.getMaxCustomers()))
            .satisfies(a -> assertThat(a.getMaxContacts()).as("check maxContacts").isEqualTo(expected.getMaxContacts()))
            .satisfies(a -> assertThat(a.getMaxQuotations()).as("check maxQuotations").isEqualTo(expected.getMaxQuotations()))
            .satisfies(a -> assertThat(a.getMaxComplaints()).as("check maxComplaints").isEqualTo(expected.getMaxComplaints()))
            .satisfies(a ->
                assertThat(a.getPricePerMonth())
                    .as("check pricePerMonth")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPricePerMonth())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanUpdatableRelationshipsEquals(Plan expected, Plan actual) {
        // empty method
    }
}
