package com.mgs.domain;

import static com.mgs.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class QuotationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAllPropertiesEquals(Quotation expected, Quotation actual) {
        assertQuotationAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAllUpdatablePropertiesEquals(Quotation expected, Quotation actual) {
        assertQuotationUpdatableFieldsEquals(expected, actual);
        assertQuotationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationAutoGeneratedPropertiesEquals(Quotation expected, Quotation actual) {
        assertThat(actual)
            .as("Verify Quotation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationUpdatableFieldsEquals(Quotation expected, Quotation actual) {
        assertThat(actual)
            .as("Verify Quotation relevant properties")
            .satisfies(a -> assertThat(a.getQuoteNumber()).as("check quoteNumber").isEqualTo(expected.getQuoteNumber()))
            .satisfies(a -> assertThat(a.getEstimateDate()).as("check estimateDate").isEqualTo(expected.getEstimateDate()))
            .satisfies(a -> assertThat(a.getValidUntil()).as("check validUntil").isEqualTo(expected.getValidUntil()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRevisionNumber()).as("check revisionNumber").isEqualTo(expected.getRevisionNumber()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getItemDiscountTotal())
                    .as("check itemDiscountTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getItemDiscountTotal())
            )
            .satisfies(a -> assertThat(a.getGlobalDiscountType()).as("check globalDiscountType").isEqualTo(expected.getGlobalDiscountType())
            )
            .satisfies(a ->
                assertThat(a.getGlobalDiscountValue())
                    .as("check globalDiscountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getGlobalDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getGlobalDiscountAmount())
                    .as("check globalDiscountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getGlobalDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxableAmount())
                    .as("check taxableAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableAmount())
            )
            .satisfies(a ->
                assertThat(a.getTotalTax()).as("check totalTax").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalTax())
            )
            .satisfies(a ->
                assertThat(a.getShippingAmount())
                    .as("check shippingAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getShippingAmount())
            )
            .satisfies(a ->
                assertThat(a.getOtherChargesAmount())
                    .as("check otherChargesAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOtherChargesAmount())
            )
            .satisfies(a ->
                assertThat(a.getRoundOffAmount())
                    .as("check roundOffAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRoundOffAmount())
            )
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getHeaderNotes()).as("check headerNotes").isEqualTo(expected.getHeaderNotes()))
            .satisfies(a -> assertThat(a.getFooterNotes()).as("check footerNotes").isEqualTo(expected.getFooterNotes()))
            .satisfies(a -> assertThat(a.getTermsAndConditions()).as("check termsAndConditions").isEqualTo(expected.getTermsAndConditions())
            )
            .satisfies(a -> assertThat(a.getReferenceNumber()).as("check referenceNumber").isEqualTo(expected.getReferenceNumber()))
            .satisfies(a -> assertThat(a.getLastSentAt()).as("check lastSentAt").isEqualTo(expected.getLastSentAt()))
            .satisfies(a -> assertThat(a.getPdfTemplateCode()).as("check pdfTemplateCode").isEqualTo(expected.getPdfTemplateCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationUpdatableRelationshipsEquals(Quotation expected, Quotation actual) {
        assertThat(actual)
            .as("Verify Quotation relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getLead()).as("check lead").isEqualTo(expected.getLead()))
            .satisfies(a -> assertThat(a.getCreatedByUser()).as("check createdByUser").isEqualTo(expected.getCreatedByUser()));
    }
}
