package com.mgs.domain;

import static com.mgs.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class QuotationItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationItemAllPropertiesEquals(QuotationItem expected, QuotationItem actual) {
        assertQuotationItemAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotationItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationItemAllUpdatablePropertiesEquals(QuotationItem expected, QuotationItem actual) {
        assertQuotationItemUpdatableFieldsEquals(expected, actual);
        assertQuotationItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationItemAutoGeneratedPropertiesEquals(QuotationItem expected, QuotationItem actual) {
        assertThat(actual)
            .as("Verify QuotationItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationItemUpdatableFieldsEquals(QuotationItem expected, QuotationItem actual) {
        assertThat(actual)
            .as("Verify QuotationItem relevant properties")
            .satisfies(a -> assertThat(a.getProductName()).as("check productName").isEqualTo(expected.getProductName()))
            .satisfies(a -> assertThat(a.getProductSku()).as("check productSku").isEqualTo(expected.getProductSku()))
            .satisfies(a -> assertThat(a.getProductDescription()).as("check productDescription").isEqualTo(expected.getProductDescription())
            )
            .satisfies(a -> assertThat(a.getUnitLabel()).as("check unitLabel").isEqualTo(expected.getUnitLabel()))
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a -> assertThat(a.getDiscountType()).as("check discountType").isEqualTo(expected.getDiscountType()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxableAmount())
                    .as("check taxableAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxRate()).as("check taxRate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxRate())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getLineTotal()).as("check lineTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLineTotal())
            )
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotationItemUpdatableRelationshipsEquals(QuotationItem expected, QuotationItem actual) {
        assertThat(actual)
            .as("Verify QuotationItem relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getQuotation()).as("check quotation").isEqualTo(expected.getQuotation()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
