package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAllPropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertReportTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertReportTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAllUpdatablePropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertReportTemplateUpdatableFieldsEquals(expected, actual);
        assertReportTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAutoGeneratedPropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertThat(actual)
            .as("Verify ReportTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateUpdatableFieldsEquals(ReportTemplate expected, ReportTemplate actual) {
        assertThat(actual)
            .as("Verify ReportTemplate relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getConfigJson()).as("check configJson").isEqualTo(expected.getConfigJson()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateUpdatableRelationshipsEquals(ReportTemplate expected, ReportTemplate actual) {
        assertThat(actual)
            .as("Verify ReportTemplate relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
