package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportRunAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportRunAllPropertiesEquals(ReportRun expected, ReportRun actual) {
        assertReportRunAutoGeneratedPropertiesEquals(expected, actual);
        assertReportRunAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportRunAllUpdatablePropertiesEquals(ReportRun expected, ReportRun actual) {
        assertReportRunUpdatableFieldsEquals(expected, actual);
        assertReportRunUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportRunAutoGeneratedPropertiesEquals(ReportRun expected, ReportRun actual) {
        assertThat(actual)
            .as("Verify ReportRun auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportRunUpdatableFieldsEquals(ReportRun expected, ReportRun actual) {
        assertThat(actual)
            .as("Verify ReportRun relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getFilterJson()).as("check filterJson").isEqualTo(expected.getFilterJson()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportRunUpdatableRelationshipsEquals(ReportRun expected, ReportRun actual) {
        assertThat(actual)
            .as("Verify ReportRun relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getTemplate()).as("check template").isEqualTo(expected.getTemplate()))
            .satisfies(a -> assertThat(a.getGeneratedByUser()).as("check generatedByUser").isEqualTo(expected.getGeneratedByUser()));
    }
}
