package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RolePermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolePermissionAllPropertiesEquals(RolePermission expected, RolePermission actual) {
        assertRolePermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertRolePermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolePermissionAllUpdatablePropertiesEquals(RolePermission expected, RolePermission actual) {
        assertRolePermissionUpdatableFieldsEquals(expected, actual);
        assertRolePermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolePermissionAutoGeneratedPropertiesEquals(RolePermission expected, RolePermission actual) {
        assertThat(actual)
            .as("Verify RolePermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolePermissionUpdatableFieldsEquals(RolePermission expected, RolePermission actual) {
        assertThat(actual)
            .as("Verify RolePermission relevant properties")
            .satisfies(a -> assertThat(a.getCanRead()).as("check canRead").isEqualTo(expected.getCanRead()))
            .satisfies(a -> assertThat(a.getCanCreate()).as("check canCreate").isEqualTo(expected.getCanCreate()))
            .satisfies(a -> assertThat(a.getCanUpdate()).as("check canUpdate").isEqualTo(expected.getCanUpdate()))
            .satisfies(a -> assertThat(a.getCanDelete()).as("check canDelete").isEqualTo(expected.getCanDelete()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolePermissionUpdatableRelationshipsEquals(RolePermission expected, RolePermission actual) {
        assertThat(actual)
            .as("Verify RolePermission relationships")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()));
    }
}
