package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubPipelineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubPipelineAllPropertiesEquals(SubPipeline expected, SubPipeline actual) {
        assertSubPipelineAutoGeneratedPropertiesEquals(expected, actual);
        assertSubPipelineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubPipelineAllUpdatablePropertiesEquals(SubPipeline expected, SubPipeline actual) {
        assertSubPipelineUpdatableFieldsEquals(expected, actual);
        assertSubPipelineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubPipelineAutoGeneratedPropertiesEquals(SubPipeline expected, SubPipeline actual) {
        assertThat(actual)
            .as("Verify SubPipeline auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubPipelineUpdatableFieldsEquals(SubPipeline expected, SubPipeline actual) {
        assertThat(actual)
            .as("Verify SubPipeline relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameSearch()).as("check nameSearch").isEqualTo(expected.getNameSearch()))
            .satisfies(a -> assertThat(a.getSequenceOrder()).as("check sequenceOrder").isEqualTo(expected.getSequenceOrder()))
            .satisfies(a -> assertThat(a.getProbability()).as("check probability").isEqualTo(expected.getProbability()))
            .satisfies(a -> assertThat(a.getIsClosingStage()).as("check isClosingStage").isEqualTo(expected.getIsClosingStage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubPipelineUpdatableRelationshipsEquals(SubPipeline expected, SubPipeline actual) {
        assertThat(actual)
            .as("Verify SubPipeline relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getPipeline()).as("check pipeline").isEqualTo(expected.getPipeline()));
    }
}
