package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUserAllPropertiesEquals(SystemUser expected, SystemUser actual) {
        assertSystemUserAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUserAllUpdatablePropertiesEquals(SystemUser expected, SystemUser actual) {
        assertSystemUserUpdatableFieldsEquals(expected, actual);
        assertSystemUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUserAutoGeneratedPropertiesEquals(SystemUser expected, SystemUser actual) {
        assertThat(actual)
            .as("Verify SystemUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUserUpdatableFieldsEquals(SystemUser expected, SystemUser actual) {
        assertThat(actual)
            .as("Verify SystemUser relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPasswordHash()).as("check passwordHash").isEqualTo(expected.getPasswordHash()))
            .satisfies(a -> assertThat(a.getIsSuperAdmin()).as("check isSuperAdmin").isEqualTo(expected.getIsSuperAdmin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUserUpdatableRelationshipsEquals(SystemUser expected, SystemUser actual) {
        // empty method
    }
}
