package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaskTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskTypeAllPropertiesEquals(TaskType expected, TaskType actual) {
        assertTaskTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertTaskTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskTypeAllUpdatablePropertiesEquals(TaskType expected, TaskType actual) {
        assertTaskTypeUpdatableFieldsEquals(expected, actual);
        assertTaskTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskTypeAutoGeneratedPropertiesEquals(TaskType expected, TaskType actual) {
        assertThat(actual)
            .as("Verify TaskType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskTypeUpdatableFieldsEquals(TaskType expected, TaskType actual) {
        assertThat(actual)
            .as("Verify TaskType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskTypeUpdatableRelationshipsEquals(TaskType expected, TaskType actual) {
        assertThat(actual)
            .as("Verify TaskType relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
