package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantBrandingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantBrandingAllPropertiesEquals(TenantBranding expected, TenantBranding actual) {
        assertTenantBrandingAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantBrandingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantBrandingAllUpdatablePropertiesEquals(TenantBranding expected, TenantBranding actual) {
        assertTenantBrandingUpdatableFieldsEquals(expected, actual);
        assertTenantBrandingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantBrandingAutoGeneratedPropertiesEquals(TenantBranding expected, TenantBranding actual) {
        assertThat(actual)
            .as("Verify TenantBranding auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantBrandingUpdatableFieldsEquals(TenantBranding expected, TenantBranding actual) {
        assertThat(actual)
            .as("Verify TenantBranding relevant properties")
            .satisfies(a -> assertThat(a.getLogoPath()).as("check logoPath").isEqualTo(expected.getLogoPath()))
            .satisfies(a -> assertThat(a.getLogoDarkPath()).as("check logoDarkPath").isEqualTo(expected.getLogoDarkPath()))
            .satisfies(a -> assertThat(a.getFaviconPath()).as("check faviconPath").isEqualTo(expected.getFaviconPath()))
            .satisfies(a -> assertThat(a.getPrimaryColor()).as("check primaryColor").isEqualTo(expected.getPrimaryColor()))
            .satisfies(a -> assertThat(a.getSecondaryColor()).as("check secondaryColor").isEqualTo(expected.getSecondaryColor()))
            .satisfies(a -> assertThat(a.getAccentColor()).as("check accentColor").isEqualTo(expected.getAccentColor()))
            .satisfies(a -> assertThat(a.getPdfHeaderLogoPath()).as("check pdfHeaderLogoPath").isEqualTo(expected.getPdfHeaderLogoPath()))
            .satisfies(a -> assertThat(a.getPdfFooterText()).as("check pdfFooterText").isEqualTo(expected.getPdfFooterText()))
            .satisfies(a -> assertThat(a.getPdfPrimaryColor()).as("check pdfPrimaryColor").isEqualTo(expected.getPdfPrimaryColor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantBrandingUpdatableRelationshipsEquals(TenantBranding expected, TenantBranding actual) {
        assertThat(actual)
            .as("Verify TenantBranding relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
