package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantProfileAllPropertiesEquals(TenantProfile expected, TenantProfile actual) {
        assertTenantProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantProfileAllUpdatablePropertiesEquals(TenantProfile expected, TenantProfile actual) {
        assertTenantProfileUpdatableFieldsEquals(expected, actual);
        assertTenantProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantProfileAutoGeneratedPropertiesEquals(TenantProfile expected, TenantProfile actual) {
        assertThat(actual)
            .as("Verify TenantProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantProfileUpdatableFieldsEquals(TenantProfile expected, TenantProfile actual) {
        assertThat(actual)
            .as("Verify TenantProfile relevant properties")
            .satisfies(a -> assertThat(a.getSubdomain()).as("check subdomain").isEqualTo(expected.getSubdomain()))
            .satisfies(a -> assertThat(a.getCustomDomain()).as("check customDomain").isEqualTo(expected.getCustomDomain()))
            .satisfies(a -> assertThat(a.getDomainVerified()).as("check domainVerified").isEqualTo(expected.getDomainVerified()))
            .satisfies(a -> assertThat(a.getLegalName()).as("check legalName").isEqualTo(expected.getLegalName()))
            .satisfies(a -> assertThat(a.getShortName()).as("check shortName").isEqualTo(expected.getShortName()))
            .satisfies(a -> assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getTaxId()).as("check taxId").isEqualTo(expected.getTaxId()))
            .satisfies(a -> assertThat(a.getContactPerson()).as("check contactPerson").isEqualTo(expected.getContactPerson()))
            .satisfies(a -> assertThat(a.getContactEmail()).as("check contactEmail").isEqualTo(expected.getContactEmail()))
            .satisfies(a -> assertThat(a.getContactPhone()).as("check contactPhone").isEqualTo(expected.getContactPhone()))
            .satisfies(a -> assertThat(a.getWebsiteUrl()).as("check websiteUrl").isEqualTo(expected.getWebsiteUrl()))
            .satisfies(a -> assertThat(a.getDefaultLocale()).as("check defaultLocale").isEqualTo(expected.getDefaultLocale()))
            .satisfies(a -> assertThat(a.getTimezone()).as("check timezone").isEqualTo(expected.getTimezone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantProfileUpdatableRelationshipsEquals(TenantProfile expected, TenantProfile actual) {
        assertThat(actual)
            .as("Verify TenantProfile relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }
}
