package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSubscriptionAllPropertiesEquals(TenantSubscription expected, TenantSubscription actual) {
        assertTenantSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSubscriptionAllUpdatablePropertiesEquals(TenantSubscription expected, TenantSubscription actual) {
        assertTenantSubscriptionUpdatableFieldsEquals(expected, actual);
        assertTenantSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSubscriptionAutoGeneratedPropertiesEquals(TenantSubscription expected, TenantSubscription actual) {
        assertThat(actual)
            .as("Verify TenantSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSubscriptionUpdatableFieldsEquals(TenantSubscription expected, TenantSubscription actual) {
        assertThat(actual)
            .as("Verify TenantSubscription relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getTrialEndDate()).as("check trialEndDate").isEqualTo(expected.getTrialEndDate()))
            .satisfies(a -> assertThat(a.getLastRenewedAt()).as("check lastRenewedAt").isEqualTo(expected.getLastRenewedAt()))
            .satisfies(a -> assertThat(a.getNextBillingAt()).as("check nextBillingAt").isEqualTo(expected.getNextBillingAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSubscriptionUpdatableRelationshipsEquals(TenantSubscription expected, TenantSubscription actual) {
        assertThat(actual)
            .as("Verify TenantSubscription relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
