package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantEncryptionKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantEncryptionKeyAllPropertiesEquals(TenantEncryptionKey expected, TenantEncryptionKey actual) {
        assertTenantEncryptionKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantEncryptionKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantEncryptionKeyAllUpdatablePropertiesEquals(TenantEncryptionKey expected, TenantEncryptionKey actual) {
        assertTenantEncryptionKeyUpdatableFieldsEquals(expected, actual);
        assertTenantEncryptionKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantEncryptionKeyAutoGeneratedPropertiesEquals(TenantEncryptionKey expected, TenantEncryptionKey actual) {
        assertThat(actual)
            .as("Verify TenantEncryptionKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantEncryptionKeyUpdatableFieldsEquals(TenantEncryptionKey expected, TenantEncryptionKey actual) {
        assertThat(actual)
            .as("Verify TenantEncryptionKey relevant properties")
            .satisfies(a -> assertThat(a.getKeyVersion()).as("check keyVersion").isEqualTo(expected.getKeyVersion()))
            .satisfies(a -> assertThat(a.getEncryptedDataKey()).as("check encryptedDataKey").isEqualTo(expected.getEncryptedDataKey()))
            .satisfies(a -> assertThat(a.getPinHash()).as("check pinHash").isEqualTo(expected.getPinHash()))
            .satisfies(a -> assertThat(a.getPinSalt()).as("check pinSalt").isEqualTo(expected.getPinSalt()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantEncryptionKeyUpdatableRelationshipsEquals(TenantEncryptionKey expected, TenantEncryptionKey actual) {
        assertThat(actual)
            .as("Verify TenantEncryptionKey relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
