package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserHierarchyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHierarchyAllPropertiesEquals(UserHierarchy expected, UserHierarchy actual) {
        assertUserHierarchyAutoGeneratedPropertiesEquals(expected, actual);
        assertUserHierarchyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHierarchyAllUpdatablePropertiesEquals(UserHierarchy expected, UserHierarchy actual) {
        assertUserHierarchyUpdatableFieldsEquals(expected, actual);
        assertUserHierarchyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHierarchyAutoGeneratedPropertiesEquals(UserHierarchy expected, UserHierarchy actual) {
        assertThat(actual)
            .as("Verify UserHierarchy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHierarchyUpdatableFieldsEquals(UserHierarchy expected, UserHierarchy actual) {
        assertThat(actual)
            .as("Verify UserHierarchy relevant properties")
            .satisfies(a -> assertThat(a.getRelationshipType()).as("check relationshipType").isEqualTo(expected.getRelationshipType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHierarchyUpdatableRelationshipsEquals(UserHierarchy expected, UserHierarchy actual) {
        assertThat(actual)
            .as("Verify UserHierarchy relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getParentUser()).as("check parentUser").isEqualTo(expected.getParentUser()))
            .satisfies(a -> assertThat(a.getChildUser()).as("check childUser").isEqualTo(expected.getChildUser()));
    }
}
