package com.mgs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDepartmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDepartmentAllPropertiesEquals(UserDepartment expected, UserDepartment actual) {
        assertUserDepartmentAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDepartmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDepartmentAllUpdatablePropertiesEquals(UserDepartment expected, UserDepartment actual) {
        assertUserDepartmentUpdatableFieldsEquals(expected, actual);
        assertUserDepartmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDepartmentAutoGeneratedPropertiesEquals(UserDepartment expected, UserDepartment actual) {
        assertThat(actual)
            .as("Verify UserDepartment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDepartmentUpdatableFieldsEquals(UserDepartment expected, UserDepartment actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDepartmentUpdatableRelationshipsEquals(UserDepartment expected, UserDepartment actual) {
        assertThat(actual)
            .as("Verify UserDepartment relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()));
    }
}
